// Plant Encyclopedia v1 — structured reference data.
// Kept factually consistent with claims already published in the
// Indoor Plants and Kitchen Gardening article pillars (see guideHref).

const plants = [
  {
    slug: "money-plant-pothos",
    commonName: "Money Plant (Pothos)",
    scientificName: "Epipremnum aureum",
    category: "Indoor",
    light: "Low light",
    water: "Every 6-8 days",
    difficulty: "Easy",
    petSafe: false,
    matureSize: "Trailing vine, 1-2m+ if given support",
    note: "The default apartment plant for a reason — it grows in a bottle of water on a shelf with no soil at all. Keep it off low tables if you have a cat or dog that chews leaves; the sap irritates mouths.",
    guideHref: "/indoor-plants/low-light-indoor-plants-indian-apartments",
  },
  {
    slug: "snake-plant",
    commonName: "Snake Plant",
    scientificName: "Dracaena trifasciata",
    category: "Indoor",
    light: "Low light",
    water: "Every 12-14 days",
    difficulty: "Easy",
    petSafe: false,
    matureSize: "60-90 cm tall, upright",
    note: "The plant most likely to survive a week you forget about it entirely — overwatering kills it far faster than neglect does. Fine for most homes but keep it away from a puppy that eats everything in reach.",
    guideHref: "/indoor-plants/low-light-indoor-plants-indian-apartments",
  },
  {
    slug: "zz-plant",
    commonName: "ZZ Plant",
    scientificName: "Zamioculcas zamiifolia",
    category: "Indoor",
    light: "Low light",
    water: "Every 12-14 days",
    difficulty: "Easy",
    petSafe: false,
    matureSize: "45-75 cm tall",
    note: "Stores water in underground rhizomes, which is why it tolerates a corner several feet from any window better than almost anything else sold in Indian nurseries. Keep it out of reach of curious pets.",
    guideHref: "/indoor-plants/low-light-indoor-plants-indian-apartments",
  },
  {
    slug: "peace-lily",
    commonName: "Peace Lily",
    scientificName: "Spathiphyllum wallisii",
    category: "Indoor",
    light: "Low light",
    water: "Every 4-5 days",
    difficulty: "Moderate",
    petSafe: false,
    matureSize: "40-60 cm tall",
    note: "Droops dramatically the moment it needs water and recovers within hours of a drink, which makes it one of the easiest plants to read. Keep it out of reach of pets that chew leaves.",
    guideHref: "/indoor-plants/low-light-indoor-plants-indian-apartments",
  },
  {
    slug: "spider-plant",
    commonName: "Spider Plant",
    scientificName: "Chlorophytum comosum",
    category: "Indoor",
    light: "Low light",
    water: "Every 7-9 days",
    difficulty: "Easy",
    petSafe: true,
    matureSize: "30-45 cm, with trailing plantlets",
    note: "Shrugs off Indian tap water hardness better than most houseplants and throws out baby plantlets you can pot up for free. A safe pick if you have cats that like to chew leaves.",
    guideHref: "/indoor-plants/low-light-indoor-plants-indian-apartments",
  },
  {
    slug: "areca-palm",
    commonName: "Areca Palm",
    scientificName: "Dypsis lutescens",
    category: "Indoor",
    light: "Partial sun",
    water: "Every 5-7 days",
    difficulty: "Moderate",
    petSafe: true,
    matureSize: "1.8-3m indoors, in a large pot",
    note: "Wants bright indirect light near a large window rather than a dim corner, and rewards it by filling a living room fast. One of the few statement-sized indoor plants that's genuinely safe around pets.",
    guideHref: "/indoor-plants/pet-safe-indoor-plants-india",
  },
  {
    slug: "aloe-vera",
    commonName: "Aloe Vera",
    scientificName: "Aloe vera",
    category: "Balcony",
    light: "Full sun",
    water: "Every 14-18 days",
    difficulty: "Easy",
    petSafe: false,
    matureSize: "30-45 cm rosette",
    note: "Wants a sunny balcony ledge, not a dim windowsill — indoors it tends to grow pale and leggy reaching for light. Handy for minor kitchen burns, but keep it away from pets since the plant itself is toxic if eaten.",
    guideHref: "/indoor-plants/pet-safe-indoor-plants-india",
  },
  {
    slug: "curry-leaf-plant",
    commonName: "Curry Leaf Plant",
    scientificName: "Murraya koenigii",
    category: "Kitchen",
    light: "Full sun",
    water: "Every 5-7 days",
    difficulty: "Moderate",
    petSafe: true,
    matureSize: "1.5-2.5m if left unpruned",
    note: "Slow to establish in the first year but nearly permanent once it does — a single well-fed plant in a sunny corner can supply a household indefinitely. Regular harvesting keeps it bushy instead of leggy.",
  },
  {
    slug: "tulsi-holy-basil",
    commonName: "Tulsi (Holy Basil)",
    scientificName: "Ocimum tenuiflorum",
    category: "Kitchen",
    light: "Full sun",
    water: "Every 2-3 days",
    difficulty: "Easy",
    petSafe: true,
    matureSize: "45-60 cm",
    note: "Grows easily from seed or a cutting and is one of the few plants that genuinely thrives in a small courtyard pot with full sun exposure. Pinch flower spikes regularly to keep leaf production going.",
  },
  {
    slug: "marigold",
    commonName: "Marigold",
    scientificName: "Tagetes erecta",
    category: "Balcony",
    light: "Full sun",
    water: "Every 3-4 days",
    difficulty: "Easy",
    petSafe: false,
    matureSize: "30-45 cm",
    note: "Fast from seed to flower — usually 6-8 weeks — and doubles as a natural pest deterrent for vegetable containers nearby. The sap can mildly irritate pets that chew on it, so keep pots out of reach if that's a concern.",
  },
  {
    slug: "hibiscus",
    commonName: "Hibiscus",
    scientificName: "Hibiscus rosa-sinensis",
    category: "Balcony",
    light: "Full sun",
    water: "Every 3-4 days",
    difficulty: "Moderate",
    petSafe: true,
    matureSize: "1.5-2.5m shrub, prunable to size",
    note: "Needs a genuinely large container — at least 14-16 inches — to flower well long-term, which is why potted hibiscus often disappoints on a small balcony. Feed regularly through the growing season for continuous blooms.",
  },
  {
    slug: "jade-plant",
    commonName: "Jade Plant",
    scientificName: "Crassula ovata",
    category: "Indoor",
    light: "Partial sun",
    water: "Every 14-18 days",
    difficulty: "Easy",
    petSafe: false,
    matureSize: "30-60 cm",
    note: "A succulent that tolerates a bright indoor windowsill as well as a balcony, making it one of the more flexible plants on this list for apartments with limited outdoor space. Toxic to pets if chewed, so place it out of paw's reach.",
  },
  {
    slug: "boston-fern",
    commonName: "Boston Fern",
    scientificName: "Nephrolepis exaltata",
    category: "Indoor",
    light: "Low light",
    water: "Every 3-4 days",
    difficulty: "Moderate",
    petSafe: true,
    matureSize: "45-60 cm spread",
    note: "Wants humidity a typical living room doesn't have, so a bathroom with a window or a spot near the kitchen sink usually works better than a bedroom shelf. Non-toxic, so it's a safe choice for a household with pets.",
    guideHref: "/indoor-plants/pet-safe-indoor-plants-india",
  },
  {
    slug: "calathea",
    commonName: "Calathea",
    scientificName: "Calathea (Goeppertia) spp.",
    category: "Indoor",
    light: "Low light",
    water: "Every 3-4 days",
    difficulty: "Challenging",
    petSafe: true,
    matureSize: "30-50 cm",
    note: "Fussy about water quality and humidity — leaf edges brown quickly with hard tap water or dry indoor air, so filtered or rested water works better. Worth the extra effort for a pet-safe plant with genuinely striking leaf patterns.",
    guideHref: "/indoor-plants/pet-safe-indoor-plants-india",
  },
  {
    slug: "coriander",
    commonName: "Coriander",
    scientificName: "Coriandrum sativum",
    category: "Kitchen",
    light: "Partial sun",
    water: "Every 2-3 days",
    difficulty: "Moderate",
    petSafe: true,
    matureSize: "20-30 cm",
    note: "Grows from cracked kitchen-spice seed in days and is ready to harvest in three to four weeks, but bolts fast once temperatures cross around 30°C — best sown October to February in most Indian cities.",
    guideHref: "/kitchen-gardening/growing-coriander-mint-containers-india",
  },
  {
    slug: "mint",
    commonName: "Mint",
    scientificName: "Mentha spicata",
    category: "Kitchen",
    light: "Partial sun",
    water: "Every 2-3 days",
    difficulty: "Easy",
    petSafe: true,
    matureSize: "30-45 cm, spreads aggressively",
    note: "Roots from a cutting in a glass of water within a week and grows year-round in most Indian cities. Give it its own pot — the roots spread underground fast enough to crowd out anything sharing the container.",
    guideHref: "/kitchen-gardening/growing-coriander-mint-containers-india",
  },
  {
    slug: "tomato",
    commonName: "Tomato",
    scientificName: "Solanum lycopersicum",
    category: "Kitchen",
    light: "Full sun",
    water: "Every 2 days",
    difficulty: "Challenging",
    petSafe: false,
    matureSize: "1-1.5m, needs staking or a cage",
    note: "Needs at least 12-14 inches of container depth and 5-6 hours of direct sun to fruit well — the most common reason balcony tomatoes disappoint is too small a pot. The leaves and stems are toxic to pets, so keep low branches trimmed if animals roam the balcony.",
    guideHref: "/kitchen-gardening/growing-tomatoes-chillies-balcony-containers",
  },
  {
    slug: "green-chilli",
    commonName: "Green Chilli",
    scientificName: "Capsicum annuum",
    category: "Kitchen",
    light: "Full sun",
    water: "Every 2-3 days",
    difficulty: "Moderate",
    petSafe: true,
    matureSize: "45-75 cm",
    note: "More forgiving than tomatoes on container size — a 10-inch pot works — and handles Indian balcony heat better than almost any other fruiting vegetable. One healthy plant keeps fruiting for months with regular harvesting.",
    guideHref: "/kitchen-gardening/growing-tomatoes-chillies-balcony-containers",
  },
];

export default plants;

export function getAllPlants() {
  return plants;
}

export function getPlantBySlug(slug) {
  return plants.find((plant) => plant.slug === slug);
}
