// Plant Encyclopedia v1, structured reference data.
// Kept factually consistent with claims already published in the
// Indoor Plants and Kitchen Gardening article pillars (see guideHref).

// Bump this whenever a plant is added, removed, or a growing note is
// substantively edited. Surfaced on the homepage stat line. Not
// auto-computed: doing that properly means a backend-tracked timestamp
// (see the Project Handbook, backend repo is not checked out in this
// session) or trusting git history / file mtimes at build time, both of
// which are unreliable in this project's actual Railway build
// environment. A single, easy-to-find manual constant, right next to the
// data it describes, is the honest tradeoff for now.
export const CONTENT_LAST_UPDATED = "Aug 12, 2026";

const plants = [
  {
    slug: "money-plant-pothos",
    commonName: "Money Plant (Pothos)",
    scientificName: "Epipremnum aureum",
    category: "Indoor",
    light: "Low light",
    water: "Every 6-8 days",
    difficulty: "Easy",
    petSafe: false,
    matureSize: "Trailing vine, 1-2m+ if given support",
    note: "The default apartment plant for a reason: it grows in a bottle of water on a shelf with no soil at all. Keep it off low tables if you have a cat or dog that chews leaves; the sap irritates mouths.",
    guideHref: "/indoor-plants/low-light-indoor-plants-indian-apartments",
  },
  {
    slug: "snake-plant",
    commonName: "Snake Plant",
    scientificName: "Dracaena trifasciata",
    category: "Indoor",
    light: "Low light",
    water: "Every 12-14 days",
    difficulty: "Easy",
    petSafe: false,
    matureSize: "60-90 cm tall, upright",
    note: "The plant most likely to survive a week you forget about it entirely, since overwatering kills it far faster than neglect does. Fine for most homes but keep it away from a puppy that eats everything in reach.",
    guideHref: "/indoor-plants/low-light-indoor-plants-indian-apartments",
  },
  {
    slug: "zz-plant",
    commonName: "ZZ Plant",
    scientificName: "Zamioculcas zamiifolia",
    category: "Indoor",
    light: "Low light",
    water: "Every 12-14 days",
    difficulty: "Easy",
    petSafe: false,
    matureSize: "45-75 cm tall",
    note: "Stores water in underground rhizomes, which is why it tolerates a corner several feet from any window better than almost anything else sold in Indian nurseries. Keep it out of reach of curious pets.",
    guideHref: "/indoor-plants/low-light-indoor-plants-indian-apartments",
  },
  {
    slug: "peace-lily",
    commonName: "Peace Lily",
    scientificName: "Spathiphyllum wallisii",
    category: "Indoor",
    light: "Low light",
    water: "Every 4-5 days",
    difficulty: "Moderate",
    petSafe: false,
    matureSize: "40-60 cm tall",
    note: "Droops dramatically the moment it needs water and recovers within hours of a drink, which makes it one of the easiest plants to read. Keep it out of reach of pets that chew leaves.",
    guideHref: "/indoor-plants/low-light-indoor-plants-indian-apartments",
  },
  {
    slug: "spider-plant",
    commonName: "Spider Plant",
    scientificName: "Chlorophytum comosum",
    category: "Indoor",
    light: "Low light",
    water: "Every 7-9 days",
    difficulty: "Easy",
    petSafe: true,
    matureSize: "30-45 cm, with trailing plantlets",
    note: "Shrugs off Indian tap water hardness better than most houseplants and throws out baby plantlets you can pot up for free. A safe pick if you have cats that like to chew leaves.",
    guideHref: "/indoor-plants/low-light-indoor-plants-indian-apartments",
  },
  {
    slug: "areca-palm",
    commonName: "Areca Palm",
    scientificName: "Dypsis lutescens",
    category: "Indoor",
    light: "Partial sun",
    water: "Every 5-7 days",
    difficulty: "Moderate",
    petSafe: true,
    matureSize: "1.8-3m indoors, in a large pot",
    note: "Wants bright indirect light near a large window rather than a dim corner, and rewards it by filling a living room fast. One of the few statement-sized indoor plants that's genuinely safe around pets.",
    guideHref: "/indoor-plants/pet-safe-indoor-plants-india",
  },
  {
    slug: "aloe-vera",
    commonName: "Aloe Vera",
    scientificName: "Aloe vera",
    category: "Balcony",
    light: "Full sun",
    water: "Every 14-18 days",
    difficulty: "Easy",
    petSafe: false,
    matureSize: "30-45 cm rosette",
    note: "Wants a sunny balcony ledge, not a dim windowsill. Indoors it tends to grow pale and leggy reaching for light. Handy for minor kitchen burns, but keep it away from pets since the plant itself is toxic if eaten.",
    guideHref: "/indoor-plants/pet-safe-indoor-plants-india",
  },
  {
    slug: "curry-leaf-plant",
    commonName: "Curry Leaf Plant",
    scientificName: "Murraya koenigii",
    category: "Kitchen",
    light: "Full sun",
    water: "Every 5-7 days",
    difficulty: "Moderate",
    petSafe: true,
    matureSize: "1.5-2.5m if left unpruned",
    note: "Slow to establish in the first year but nearly permanent once it does. A single well-fed plant in a sunny corner can supply a household indefinitely. Regular harvesting keeps it bushy instead of leggy.",
  },
  {
    slug: "tulsi-holy-basil",
    commonName: "Tulsi (Holy Basil)",
    scientificName: "Ocimum tenuiflorum",
    category: "Kitchen",
    light: "Full sun",
    water: "Every 2-3 days",
    difficulty: "Easy",
    petSafe: true,
    matureSize: "45-60 cm",
    note: "Grows easily from seed or a cutting and is one of the few plants that genuinely thrives in a small courtyard pot with full sun exposure. Pinch flower spikes regularly to keep leaf production going.",
  },
  {
    slug: "marigold",
    commonName: "Marigold",
    scientificName: "Tagetes erecta",
    category: "Balcony",
    light: "Full sun",
    water: "Every 3-4 days",
    difficulty: "Easy",
    petSafe: false,
    matureSize: "30-45 cm",
    note: "Fast from seed to flower, usually 6-8 weeks, and doubles as a natural pest deterrent for vegetable containers nearby. The sap can mildly irritate pets that chew on it, so keep pots out of reach if that's a concern.",
  },
  {
    slug: "hibiscus",
    commonName: "Hibiscus",
    scientificName: "Hibiscus rosa-sinensis",
    category: "Balcony",
    light: "Full sun",
    water: "Every 3-4 days",
    difficulty: "Moderate",
    petSafe: true,
    matureSize: "1.5-2.5m shrub, prunable to size",
    note: "Needs a genuinely large container, at least 14-16 inches, to flower well long-term, which is why potted hibiscus often disappoints on a small balcony. Feed regularly through the growing season for continuous blooms.",
  },
  {
    slug: "jade-plant",
    commonName: "Jade Plant",
    scientificName: "Crassula ovata",
    category: "Indoor",
    light: "Partial sun",
    water: "Every 14-18 days",
    difficulty: "Easy",
    petSafe: false,
    matureSize: "30-60 cm",
    note: "A succulent that tolerates a bright indoor windowsill as well as a balcony, making it one of the more flexible plants on this list for apartments with limited outdoor space. Toxic to pets if chewed, so place it out of paw's reach.",
  },
  {
    slug: "boston-fern",
    commonName: "Boston Fern",
    scientificName: "Nephrolepis exaltata",
    category: "Indoor",
    light: "Low light",
    water: "Every 3-4 days",
    difficulty: "Moderate",
    petSafe: true,
    matureSize: "45-60 cm spread",
    note: "Wants humidity a typical living room doesn't have, so a bathroom with a window or a spot near the kitchen sink usually works better than a bedroom shelf. Non-toxic, so it's a safe choice for a household with pets.",
    guideHref: "/indoor-plants/pet-safe-indoor-plants-india",
  },
  {
    slug: "calathea",
    commonName: "Calathea",
    scientificName: "Calathea (Goeppertia) spp.",
    category: "Indoor",
    light: "Low light",
    water: "Every 3-4 days",
    difficulty: "Challenging",
    petSafe: true,
    matureSize: "30-50 cm",
    note: "Fussy about water quality and humidity. Leaf edges brown quickly with hard tap water or dry indoor air, so filtered or rested water works better. Worth the extra effort for a pet-safe plant with genuinely striking leaf patterns.",
    guideHref: "/indoor-plants/pet-safe-indoor-plants-india",
  },
  {
    slug: "coriander",
    commonName: "Coriander",
    scientificName: "Coriandrum sativum",
    category: "Kitchen",
    light: "Partial sun",
    water: "Every 2-3 days",
    difficulty: "Moderate",
    petSafe: true,
    matureSize: "20-30 cm",
    note: "Grows from cracked kitchen-spice seed in days and is ready to harvest in three to four weeks, but bolts fast once temperatures cross around 30°C. Best sown October to February in most Indian cities.",
    guideHref: "/kitchen-gardening/growing-coriander-mint-containers-india",
  },
  {
    slug: "mint",
    commonName: "Mint",
    scientificName: "Mentha spicata",
    category: "Kitchen",
    light: "Partial sun",
    water: "Every 2-3 days",
    difficulty: "Easy",
    petSafe: true,
    matureSize: "30-45 cm, spreads aggressively",
    note: "Roots from a cutting in a glass of water within a week and grows year-round in most Indian cities. Give it its own pot, since the roots spread underground fast enough to crowd out anything sharing the container.",
    guideHref: "/kitchen-gardening/growing-coriander-mint-containers-india",
  },
  {
    slug: "tomato",
    commonName: "Tomato",
    scientificName: "Solanum lycopersicum",
    category: "Kitchen",
    light: "Full sun",
    water: "Every 2 days",
    difficulty: "Challenging",
    petSafe: false,
    matureSize: "1-1.5m, needs staking or a cage",
    note: "Needs at least 12-14 inches of container depth and 5-6 hours of direct sun to fruit well. The most common reason balcony tomatoes disappoint is too small a pot. The leaves and stems are toxic to pets, so keep low branches trimmed if animals roam the balcony.",
    guideHref: "/kitchen-gardening/growing-tomatoes-chillies-balcony-containers",
  },
  {
    slug: "green-chilli",
    commonName: "Green Chilli",
    scientificName: "Capsicum annuum",
    category: "Kitchen",
    light: "Full sun",
    water: "Every 2-3 days",
    difficulty: "Moderate",
    petSafe: true,
    matureSize: "45-75 cm",
    note: "More forgiving than tomatoes on container size (a 10-inch pot works) and handles Indian balcony heat better than almost any other fruiting vegetable. One healthy plant keeps fruiting for months with regular harvesting.",
    guideHref: "/kitchen-gardening/growing-tomatoes-chillies-balcony-containers",
  },
  {
    slug: "lemon",
    commonName: "Lemon (Nimbu)",
    scientificName: "Citrus limon",
    category: "Kitchen",
    light: "Full sun",
    water: "Every 3-4 days",
    difficulty: "Challenging",
    petSafe: false,
    matureSize: "1-2m in a large container, slower and more compact than a ground-planted tree",
    note: "Needs a genuinely large pot, 16 inches or more, with sharp drainage, since the roots resent sitting wet. Hard Indian tap water tends to push the soil alkaline over time, which shows up as yellowing between the leaf veins (iron chlorosis); a dose of chelated iron or occasional rainwater helps. Slow to fruit, often 2-3 years from a nursery sapling. The leaves, stems, and unripe fruit contain citrus oils and psoralens that are toxic to cats and dogs, so keep pots out of reach.",
  },
  {
    slug: "papaya",
    commonName: "Papaya",
    scientificName: "Carica papaya",
    category: "Kitchen",
    light: "Full sun",
    water: "Every 2-3 days",
    difficulty: "Challenging",
    petSafe: false,
    matureSize: "2-3m even in a large container or ground bed; effectively a fast-growing small tree, not container-friendly long-term",
    note: "Grows fast from seed but needs deep, very well-drained soil, since papaya roots rot quickly in waterlogged pots. Plants are male, female, or bisexual; only female or bisexual plants fruit, so a papaya grown from a random seed has roughly even odds of turning out male and never fruiting at all. Shallow roots and a top-heavy crown mean it needs shelter from strong balcony wind. The sap in the leaves and unripe fruit contains latex and papain, which irritate skin and the mouth if chewed, so treat it as not pet-safe.",
  },
  {
    slug: "fenugreek-methi",
    commonName: "Fenugreek (Methi)",
    scientificName: "Trigonella foenum-graecum",
    category: "Kitchen",
    light: "Partial sun",
    water: "Every 2-3 days",
    difficulty: "Easy",
    petSafe: true,
    matureSize: "15-30 cm if harvested young for leaves",
    note: "One of the fastest kitchen-garden crops to go from seed to plate: soak whole methi seeds (the kind sold for cooking) overnight and they germinate within days. Ready to cut as leafy methi in about 3-4 weeks; harvest cut-and-come-again a couple of times before it bolts and flowers. Tolerates partial sun better than most fruiting vegetables, which makes it a good fit for a balcony that only gets a few hours of direct light.",
  },
  {
    slug: "spinach-palak",
    commonName: "Spinach (Palak)",
    scientificName: "Spinacia oleracea",
    category: "Kitchen",
    light: "Partial sun",
    water: "Every 2-3 days",
    difficulty: "Moderate",
    petSafe: true,
    matureSize: "15-25 cm rosette",
    note: "A cool-season crop, best sown October to February in most Indian cities; it bolts and turns bitter fast once daytime temperatures climb above the mid-20s°C. Keep the soil consistently moist, since letting it dry out toughens the leaves. Harvest outer leaves and let the center keep producing rather than pulling the whole plant at once.",
  },
  {
    slug: "okra-bhindi",
    commonName: "Okra (Bhindi / Lady's Finger)",
    scientificName: "Abelmoschus esculentus",
    category: "Kitchen",
    light: "Full sun",
    water: "Every 2-3 days",
    difficulty: "Moderate",
    petSafe: true,
    matureSize: "60-90 cm",
    note: "Handles peak Indian summer heat better than tomatoes or chillies, which makes it one of the more reliable fruiting vegetables for a hot, exposed balcony. Needs a 12-inch-plus container for a decent root run. Pods turn fibrous and woody within a day or two of reaching full size, so once flowering starts it needs harvesting every 1-2 days to stay tender. The fine bristles on stems and pods can mildly irritate skin during picking.",
  },
  {
    slug: "bougainvillea",
    commonName: "Bougainvillea",
    scientificName: "Bougainvillea spectabilis",
    category: "Balcony",
    light: "Full sun",
    water: "Every 7-10 days",
    difficulty: "Easy",
    petSafe: true,
    matureSize: "Climbs several metres if trained on a trellis, or kept as a 1-1.5m compact shrub with pruning",
    note: "One of the toughest, most neglect-tolerant flowering plants for an Indian balcony, and counterintuitively flowers best when watered a little less rather than more; established plants can go 7-10 days between waterings, longer than most flowering plants on this list. Non-toxic to cats and dogs if chewed, but the sharp thorns are a real hazard on their own and worth keeping in mind around pets and small children.",
  },
  {
    slug: "jasmine-mogra",
    commonName: "Jasmine (Mogra)",
    scientificName: "Jasminum sambac",
    category: "Balcony",
    light: "Full sun",
    water: "Every 3-4 days",
    difficulty: "Moderate",
    petSafe: true,
    matureSize: "60 cm-1.5m, trainable on a trellis or kept bushy with pruning",
    note: "Rewards full sun with heavily scented flowers through summer and monsoon, but sulks and drops buds in deep shade. Watch for mealybugs and sooty mould in humid weather; regular pruning after flowering keeps it bushy rather than leggy. True jasmine (the Jasminum genus, which mogra belongs to) is non-toxic to cats and dogs; note that this is specific to true jasmine and doesn't extend to unrelated plants that share the common name \"jasmine,\" such as Carolina jessamine, which is a different, toxic genus.",
  },
  {
    slug: "rose",
    commonName: "Rose (Gulab)",
    scientificName: "Rosa spp.",
    category: "Balcony",
    light: "Full sun",
    water: "Every 3-4 days",
    difficulty: "Challenging",
    petSafe: true,
    matureSize: "1-1.5m shrub, prunable to size",
    note: "Fussier in pots than marigold or hibiscus, especially through India's humid monsoon and summer, when black spot and powdery mildew show up fast on damp foliage. Water the soil in the morning rather than the leaves in the evening, and give it a large pot (14-16 inches) plus monthly feeding for repeat blooms. Non-toxic to cats and dogs, though the thorns are their own hazard.",
  },
  {
    slug: "rubber-plant",
    commonName: "Rubber Plant",
    scientificName: "Ficus elastica",
    category: "Indoor",
    light: "Partial sun",
    water: "Every 7-9 days",
    difficulty: "Moderate",
    petSafe: false,
    matureSize: "1.5-3m indoors over years if unpruned, easily kept smaller by pruning and pot size",
    note: "Wants bright indirect light rather than a dim corner; tolerates lower light but grows slower and less glossy. Sensitive to overwatering, which shows up as black spots or root rot, and to sudden changes in light, temperature, or draughts, which cause leaf drop. The milky latex sap is irritating to skin and toxic to cats and dogs if the leaves or stems are chewed, so keep it away from curious pets.",
  },
  {
    slug: "philodendron",
    commonName: "Philodendron",
    scientificName: "Philodendron hederaceum",
    category: "Indoor",
    light: "Low light",
    water: "Every 6-8 days",
    difficulty: "Easy",
    petSafe: false,
    matureSize: "Trailing vine, 1-2m+ if given support",
    note: "Often mistaken for money plant (pothos) on a nursery shelf, but the heart-shaped leaves are thinner and softer, and new growth typically unfurls from a light pink or copper sheath. Roots readily from a cutting in a glass of water, making it one of the easiest plants on this list to propagate for free. Contains calcium oxalate crystals that irritate the mouth and cause drooling or vomiting if a cat or dog chews the leaves, so keep it out of reach.",
  },
];

export default plants;

export function getAllPlants() {
  return plants;
}

export function getPlantBySlug(slug) {
  return plants.find((plant) => plant.slug === slug);
}
